sudo: required

services:
  - docker

before_install:
  - docker build -t ktitan/glastopf .
  - docker run -d -p 127.0.0.1:80:80 --name glastopf ktitan/glastopf
  - docker ps -a

script:
  - docker ps | grep -q glastopf
  - wget http://127.0.0.1:80/phpinfo/phpinfo.html -O /dev/null
